import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import { BasketProvider } from "../context/BasketContext";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BuyerFe",
  description: "Generated by BuyerFe Web",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-screen flex flex-col bg-slate-100`}
      >
        <BasketProvider>
          <Header />
          <Toaster position="bottom-right" />
          <main className="grow"> {children}</main>
          <Footer />
        </BasketProvider>
      </body>
    </html>
  );
}
